POST  http://localhost:5000/auth/register
Content-Type: application/json

{
    "name":"Monyet Damm",
    "email": "gabrielldd@gmail.com",
    "password": "sdsafdaf"
}

###
POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "gabriellds@gmail.com",
    "password": "sdsafdaf"
}

# login with google
GET http://localhost:5000/auth/google


###
GET http://localhost:5000/users
Content-Type: application/json

